on:
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Pypi upload
    - uses: ortega2247/pypi-upload-action@v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
