on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ortega2247/pypi-upload-action@v1
      - name: Pypi upload
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
